from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
import json
import re
from pathlib import Path
from typing import Any

from factgraph.adapters.problog.rule_ext import (
    ProbLogRuleExt,
    materialize_problog_branch_probabilities,
)
from factgraph.adapters.souffle.where_compile import extract_where_variables
from factgraph.core.store.runtime import Store

_NONE_VALUE = "__none__"
_VAR_IDENT_RE = re.compile(r"[^A-Za-z0-9_]")
_AGGREGATE_KINDS = {"count", "sum", "min", "max", "mean"}
_AGGREGATE_FILTER_ATOM_KINDS = {"pred", "eq", "ne", "gt", "ge", "lt", "le", "in", "not"}
_DEFAULT_UNCERTAINTY_PROJECTION = {
    "probabilistic": {"policy": "reject"},
    "possibilistic": {"policy": "reject"},
    "fallback": "reject_unconfigured",
}


class ProbLogExportError(Exception):
    pass


@dataclass
class _CompileContext:
    next_id: int = 1
    requires_lists: bool = False

    def fresh(self, prefix: str) -> str:
        normalized = _VAR_IDENT_RE.sub("_", prefix).strip("_") or "var"
        name = f"Agg{normalized[0].upper()}{normalized[1:]}{self.next_id}"
        self.next_id += 1
        return name


def export_problog(
    store: Store,
    rule_spec: dict[str, Any],
    out_path: Path,
    *,
    uncertainty_projection: Mapping[str, Any] | None = None,
) -> None:
    if not isinstance(store, Store):
        raise ProbLogExportError("store must be Store")
    if not isinstance(rule_spec, dict):
        raise ProbLogExportError("rule_spec must be object")
    projection = _normalize_uncertainty_projection(uncertainty_projection)

    where = rule_spec.get("where")
    if not isinstance(where, list) or not where:
        raise ProbLogExportError("rule_spec.where must be non-empty list")
    bodies = _normalize_where_bodies(where)
    engine_ext = rule_spec.get("engine_ext")
    if engine_ext is not None and not isinstance(engine_ext, ProbLogRuleExt):
        raise ProbLogExportError(f"rule_spec.engine_ext must be ProbLogRuleExt, got {type(engine_ext).__name__}")
    try:
        branch_probabilities = materialize_problog_branch_probabilities(
            where=where,
            engine_ext=engine_ext,
        )
    except ValueError as exc:
        raise ProbLogExportError(str(exc)) from exc

    try:
        query_vars = extract_where_variables(where)
    except Exception as exc:
        raise ProbLogExportError(f"failed to extract query variables: {exc}") from exc

    ctx = _CompileContext()
    compiled_bodies = [_compile_body(body, ctx=ctx) for body in bodies]

    lines: list[str] = []
    lines.append("% generated by factpy problog adapter")
    lines.append(f"% query_vars={json.dumps(query_vars, ensure_ascii=False, separators=(',', ':'))}")
    lines.append("")
    if ctx.requires_lists:
        lines.append(":- use_module(library(lists)).")
        lines.append("")

    active_claims = [
        claim
        for claim in store.ledger.claims
        if not store.ledger.has_active_revocation(claim.asrt_id)
    ]
    active_claims.sort(key=lambda row: row.asrt_id)

    for claim in active_claims:
        prob = _claim_probability(store, claim.asrt_id, uncertainty_projection=projection)
        value_term = _claim_value_term(claim.rest_terms)
        lines.append(
            f"{_format_probability(prob)}::edb_fact("
            f"{_to_problog_literal(claim.asrt_id)}, "
            f"{_to_problog_literal(claim.pred_id)}, "
            f"{_to_problog_literal(claim.e_ref)}, "
            f"{value_term}"
            ")."
        )

    if lines and lines[-1] != "":
        lines.append("")

    for idx, body in enumerate(bodies):
        branch_head = _predicate_call(f"rule_body_{idx}", query_vars)
        compiled_body = compiled_bodies[idx]
        lines.append(f"{_format_probability(branch_probabilities[idx])}::{branch_head} :- {compiled_body}.")

    answer_head = _predicate_call("answer", query_vars)
    for idx in range(len(bodies)):
        branch_head = _predicate_call(f"rule_body_{idx}", query_vars)
        lines.append(f"{answer_head} :- {branch_head}.")
    lines.append(f"query({answer_head}).")

    path = Path(out_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8", newline="\n")


def _normalize_where_bodies(where: list[Any]) -> list[list[Any]]:
    if not where:
        raise ProbLogExportError("where must be non-empty list")
    if all(isinstance(item, list) for item in where):
        bodies = [list(branch) for branch in where]
        if any(not branch for branch in bodies):
            raise ProbLogExportError("where OR branch must be non-empty")
        return bodies
    return [list(where)]


def _claim_probability(
    store: Store,
    asrt_id: str,
    *,
    uncertainty_projection: dict[str, Any] | None = None,
) -> float:
    projection = (
        uncertainty_projection
        if uncertainty_projection is not None
        else dict(_DEFAULT_UNCERTAINTY_PROJECTION)
    )
    annotations = store.ledger.find_annotations(
        asrt_id=asrt_id,
        namespace="problog",
        category="semantic",
        key="probability",
    )
    if annotations:
        for row in reversed(annotations):
            value = row.value
            if isinstance(value, bool):
                continue
            if isinstance(value, (int, float)):
                prob = float(value)
                if prob <= 0.0 or prob > 1.0:
                    raise ProbLogExportError(
                        f"problog/semantic/probability out of range for asrt_id={asrt_id}: {prob}"
                    )
                return prob
            raise ProbLogExportError(
                f"problog/semantic/probability must be numeric for asrt_id={asrt_id}"
            )

    shared_annotations = store.ledger.find_annotations(
        asrt_id=asrt_id,
        namespace="shared",
        category="semantic",
        key="probability",
    )
    if shared_annotations:
        for row in reversed(shared_annotations):
            value = row.value
            if isinstance(value, bool):
                continue
            if isinstance(value, (int, float)):
                prob = float(value)
                if prob <= 0.0 or prob > 1.0:
                    raise ProbLogExportError(
                        f"shared/semantic/probability out of range for asrt_id={asrt_id}: {prob}"
                    )
                return prob
            raise ProbLogExportError(
                f"shared/semantic/probability must be numeric for asrt_id={asrt_id}"
            )

    raw_probability = _claim_raw_uncertainty_probability(
        store,
        asrt_id,
        uncertainty_projection=projection,
    )
    if raw_probability is not None:
        return raw_probability

    return 1.0


def _claim_raw_uncertainty_probability(
    store: Store,
    asrt_id: str,
    *,
    uncertainty_projection: dict[str, Any],
) -> float | None:
    raw_kind_rows = store.ledger.find_annotations(
        asrt_id=asrt_id,
        namespace="shared",
        category="semantic",
        key="raw_kind",
    )
    bound_rows = store.ledger.find_annotations(
        asrt_id=asrt_id,
        namespace="shared",
        category="semantic",
        key="bound",
    )
    if not raw_kind_rows and not bound_rows:
        return None
    if not raw_kind_rows or not bound_rows:
        raise ProbLogExportError(
            f"shared raw uncertainty annotations must include raw_kind and bound for asrt_id={asrt_id}"
        )

    raw_kind = raw_kind_rows[-1].value
    if not isinstance(raw_kind, str):
        raise ProbLogExportError(f"shared/semantic/raw_kind must be string for asrt_id={asrt_id}")
    bound = _normalize_uncertainty_bound(bound_rows[-1].value, asrt_id=asrt_id)

    config = uncertainty_projection.get(raw_kind)
    if config is None:
        return _fallback_uncertainty_probability(
            uncertainty_projection.get("fallback", "reject_unconfigured"),
            raw_kind=raw_kind,
            asrt_id=asrt_id,
        )
    if not isinstance(config, Mapping):
        raise ProbLogExportError(f"uncertainty_projection.{raw_kind} must be object")
    policy = config.get("policy")
    if policy == "reject":
        raise ProbLogExportError(
            f"uncertainty_projection.{raw_kind}.policy=reject for asrt_id={asrt_id}"
        )
    if policy == "lower":
        return bound[0]
    if policy == "midpoint":
        return (bound[0] + bound[1]) / 2.0
    if policy == "upper":
        return bound[1]
    if policy == "identity_probability":
        if raw_kind != "probabilistic":
            raise ProbLogExportError("identity_probability only supports raw_kind='probabilistic'")
        if bound[0] != bound[1]:
            raise ProbLogExportError(
                f"identity_probability requires degenerate bound for asrt_id={asrt_id}"
            )
        return bound[0]
    if policy in {"probability_interval", "possibility_interval"}:
        raise ProbLogExportError(
            f"uncertainty_projection.{raw_kind}.policy={policy} is not supported by ProbLog point export"
        )
    raise ProbLogExportError(f"unsupported uncertainty_projection.{raw_kind}.policy: {policy!r}")


def _fallback_uncertainty_probability(raw_fallback: Any, *, raw_kind: str, asrt_id: str) -> float:
    if raw_fallback == "reject_unconfigured":
        raise ProbLogExportError(
            f"uncertainty_projection has no policy for raw_kind={raw_kind!r} at asrt_id={asrt_id}"
        )
    if raw_fallback in {"warn_default", "use_default"}:
        return 1.0
    raise ProbLogExportError(f"unsupported uncertainty_projection.fallback: {raw_fallback!r}")


def _normalize_uncertainty_projection(raw: Mapping[str, Any] | None) -> dict[str, Any]:
    projection = dict(_DEFAULT_UNCERTAINTY_PROJECTION)
    if raw:
        projection.update(dict(raw))
    return projection


def _normalize_uncertainty_bound(value: Any, *, asrt_id: str) -> tuple[float, float]:
    if not isinstance(value, list) or len(value) != 2:
        raise ProbLogExportError(f"shared/semantic/bound must be a two-element list for asrt_id={asrt_id}")
    lower_raw, upper_raw = value
    if isinstance(lower_raw, bool) or isinstance(upper_raw, bool):
        raise ProbLogExportError(f"shared/semantic/bound values must be numeric for asrt_id={asrt_id}")
    if not isinstance(lower_raw, (int, float)) or not isinstance(upper_raw, (int, float)):
        raise ProbLogExportError(f"shared/semantic/bound values must be numeric for asrt_id={asrt_id}")
    lower = float(lower_raw)
    upper = float(upper_raw)
    if lower < 0.0 or upper > 1.0 or lower > upper:
        raise ProbLogExportError(f"shared/semantic/bound must satisfy 0 <= lower <= upper <= 1 for asrt_id={asrt_id}")
    return (lower, upper)


def _claim_value_term(rest_terms: list[tuple[str, Any]]) -> str:
    if not isinstance(rest_terms, list):
        raise ProbLogExportError("claim.rest_terms must be list")
    if len(rest_terms) == 0:
        return _to_problog_literal(_NONE_VALUE)
    if len(rest_terms) == 1:
        tag, value = rest_terms[0]
        return _tagged_value_to_problog_term(str(tag), value)
    encoded = json.dumps(rest_terms, ensure_ascii=False, separators=(",", ":"), sort_keys=True)
    return _to_problog_literal(encoded)


def _tagged_value_to_problog_term(tag: str, value: Any) -> str:
    if tag in {"string", "entity_ref", "uuid"}:
        return _to_problog_literal(str(value))
    if tag in {"int", "time"}:
        if isinstance(value, bool) or not isinstance(value, int):
            raise ProbLogExportError(f"expected int for tag={tag}")
        return str(value)
    if tag == "bool":
        if not isinstance(value, bool):
            raise ProbLogExportError("expected bool for tag=bool")
        return "true" if value else "false"
    if tag == "float64":
        if isinstance(value, bool):
            raise ProbLogExportError("expected float for tag=float64")
        if isinstance(value, float):
            return repr(value)
        if isinstance(value, str):
            return _to_problog_literal(value)
        raise ProbLogExportError("expected float|hex-string for tag=float64")
    if tag in {"bytes", "json"}:
        return _to_problog_literal(json.dumps(value, ensure_ascii=False, separators=(",", ":"), sort_keys=True))
    return _to_problog_literal(str(value))


def _format_probability(prob: float) -> str:
    if isinstance(prob, bool) or not isinstance(prob, float):
        raise ProbLogExportError("probability must be float")
    if prob <= 0.0 or prob > 1.0:
        raise ProbLogExportError("probability must be within (0,1]")
    return f"{prob:.12g}"


def _predicate_call(name: str, vars_in_order: list[str]) -> str:
    if not vars_in_order:
        return name
    args = ", ".join(_to_problog_term(token) for token in vars_in_order)
    return f"{name}({args})"


def _compile_body(body: list[Any], *, ctx: _CompileContext | None = None) -> str:
    if not isinstance(body, list) or not body:
        raise ProbLogExportError("where body must be non-empty list")
    context = ctx if ctx is not None else _CompileContext()
    return ", ".join(_compile_atom(atom, ctx=context) for atom in body)


def _compile_atom(atom: Any, *, ctx: _CompileContext | None = None) -> str:
    if not isinstance(atom, tuple) or not atom:
        raise ProbLogExportError(f"unsupported where atom: {atom!r}")
    context = ctx if ctx is not None else _CompileContext()
    kind = atom[0]

    if kind == "pred":
        if len(atom) != 3:
            raise ProbLogExportError("pred atom must be ('pred', pred_id, terms)")
        pred_id, terms = atom[1], atom[2]
        if not isinstance(pred_id, str) or not pred_id:
            raise ProbLogExportError("pred_id must be non-empty string")
        if not isinstance(terms, list) or not terms:
            raise ProbLogExportError("pred terms must be non-empty list")
        if len(terms) == 1:
            return (
                "edb_fact(_, "
                f"{_to_problog_literal(pred_id)}, "
                f"{_to_problog_term(terms[0])}, "
                "_)"
            )
        if len(terms) == 2:
            return (
                "edb_fact(_, "
                f"{_to_problog_literal(pred_id)}, "
                f"{_to_problog_term(terms[0])}, "
                f"{_to_problog_term(terms[1])}"
                ")"
            )
        raise ProbLogExportError(f"pred atom arity > 2 is not supported in problog export: {pred_id}")

    if kind == "eq":
        if len(atom) != 3:
            raise ProbLogExportError("eq atom must be ('eq', lhs, rhs)")
        if _is_tuple_operand(atom[1]) or _is_tuple_operand(atom[2]):
            return _compile_cmp_with_aggregate("eq", atom[1], atom[2], ctx=context)
        return f"{_to_problog_term(atom[1])} = {_to_problog_term(atom[2])}"

    if kind == "ne":
        if len(atom) != 3:
            raise ProbLogExportError("ne atom must be ('ne', lhs, rhs)")
        if _is_tuple_operand(atom[1]) or _is_tuple_operand(atom[2]):
            return _compile_cmp_with_aggregate("ne", atom[1], atom[2], ctx=context)
        return f"{_to_problog_term(atom[1])} \\= {_to_problog_term(atom[2])}"

    if kind in {"gt", "ge", "lt", "le"}:
        if len(atom) != 3:
            raise ProbLogExportError(f"{kind} atom must have 2 operands")
        if _is_tuple_operand(atom[1]) or _is_tuple_operand(atom[2]):
            return _compile_cmp_with_aggregate(kind, atom[1], atom[2], ctx=context)
        op = {"gt": ">", "ge": ">=", "lt": "<", "le": "=<"}[kind]
        return f"{_to_problog_term(atom[1])} {op} {_to_problog_term(atom[2])}"

    if kind in {"add", "sub"}:
        if len(atom) != 4:
            raise ProbLogExportError(f"{kind} atom must be ({kind!r}, out, lhs, rhs)")
        op = {"add": "+", "sub": "-"}[kind]
        out = _to_problog_arith_output(atom[1], kind)
        lhs = _to_problog_arith_term(atom[2])
        rhs = _to_problog_arith_term(atom[3])
        return f"{out} is {lhs} {op} {rhs}"

    if kind == "neg":
        if len(atom) != 3:
            raise ProbLogExportError("neg atom must be ('neg', out, value)")
        out = _to_problog_arith_output(atom[1], kind)
        value = _to_problog_arith_term(atom[2])
        return f"{out} is -{value}"

    if kind in {"addc", "mulc"}:
        if len(atom) != 4:
            raise ProbLogExportError(f"{kind} atom must be ({kind!r}, out, var, const)")
        op = {"addc": "+", "mulc": "*"}[kind]
        out = _to_problog_arith_output(atom[1], kind)
        var = _to_problog_arith_term(atom[2])
        const = _to_problog_arith_term(atom[3])
        return f"{out} is {var} {op} {const}"

    if kind == "in":
        if len(atom) != 3:
            raise ProbLogExportError("in atom must be ('in', var, values)")
        lhs = _to_problog_term(atom[1])
        values = atom[2]
        if not isinstance(values, list) or not values:
            raise ProbLogExportError("in values must be non-empty list")
        parts = [f"{lhs} = {_to_problog_term(value)}" for value in values]
        return f"({' ; '.join(parts)})"

    if kind == "not":
        if len(atom) != 2:
            raise ProbLogExportError("not atom must be ('not', body)")
        not_body = atom[1]
        branches = _normalize_not_bodies(not_body)
        branch_terms = [", ".join(_compile_atom(entry, ctx=context) for entry in branch) for branch in branches]
        if len(branch_terms) == 1:
            inner = branch_terms[0]
        else:
            inner = " ; ".join(f"({term})" for term in branch_terms)
        return f"\\+({inner})"

    raise ProbLogExportError(f"unsupported where atom kind for problog export: {kind}")


def _is_tuple_operand(value: Any) -> bool:
    return isinstance(value, tuple)


def _compile_cmp_with_aggregate(kind: str, lhs: Any, rhs: Any, *, ctx: _CompileContext) -> str:
    op = {"eq": "=", "ne": "\\=", "gt": ">", "ge": ">=", "lt": "<", "le": "=<"}[kind]
    lhs_goals, lhs_term = _compile_cmp_operand(lhs, kind=kind, ctx=ctx)
    rhs_goals, rhs_term = _compile_cmp_operand(rhs, kind=kind, ctx=ctx)
    return ", ".join([*lhs_goals, *rhs_goals, f"{lhs_term} {op} {rhs_term}"])


def _compile_cmp_operand(value: Any, *, kind: str, ctx: _CompileContext) -> tuple[list[str], str]:
    if isinstance(value, tuple):
        return _compile_aggregate_parts(value, ctx=ctx)
    if kind in {"gt", "ge", "lt", "le"}:
        return [], _to_problog_arith_term(value)
    return [], _to_problog_term(value)


def _compile_aggregate_parts(aggregate: tuple[Any, ...], *, ctx: _CompileContext) -> tuple[list[str], str]:
    kind, target_var, filter_atoms = _validate_aggregate_shape(aggregate)
    ctx.requires_lists = True
    list_var = ctx.fresh("List")
    result_var = ctx.fresh("Result")
    filter_goal = _compile_aggregate_filter(filter_atoms, ctx=ctx)

    if kind == "count":
        return [
            f"findall(1, ({filter_goal}), {list_var})",
            f"length({list_var}, {result_var})",
        ], result_var

    target = _to_problog_arith_term(target_var)
    goals = [f"findall({target}, ({filter_goal}), {list_var})"]
    if kind == "sum":
        goals.append(f"sum_list({list_var}, {result_var})")
    elif kind == "min":
        goals.extend([f"{list_var} = [_|_]", f"min_list({list_var}, {result_var})"])
    elif kind == "max":
        goals.extend([f"{list_var} = [_|_]", f"max_list({list_var}, {result_var})"])
    elif kind == "mean":
        sum_var = ctx.fresh("Sum")
        count_var = ctx.fresh("Count")
        goals.extend(
            [
                f"{list_var} = [_|_]",
                f"sum_list({list_var}, {sum_var})",
                f"length({list_var}, {count_var})",
                f"{result_var} is {sum_var} / {count_var}",
            ]
        )
    return goals, result_var


def _compile_aggregate_filter(filter_atoms: list[Any], *, ctx: _CompileContext) -> str:
    return ", ".join(_compile_atom(atom, ctx=ctx) for atom in filter_atoms)


def _validate_aggregate_shape(aggregate: tuple[Any, ...]) -> tuple[str, str | None, list[Any]]:
    if not isinstance(aggregate, tuple) or len(aggregate) != 3:
        raise ProbLogExportError("aggregate term must be (kind, target_var, filter_atoms)")
    kind, target_var, filter_atoms = aggregate
    if not isinstance(kind, str) or kind not in _AGGREGATE_KINDS:
        raise ProbLogExportError(f"unsupported aggregate kind: {kind}")
    if kind == "count":
        if target_var is not None:
            raise ProbLogExportError("count aggregate target must be None")
    elif not (isinstance(target_var, str) and target_var.startswith("$")):
        raise ProbLogExportError(f"{kind} aggregate target must be a variable token")
    if not isinstance(filter_atoms, list) or not filter_atoms:
        raise ProbLogExportError("aggregate filter must be non-empty list")
    _validate_aggregate_filter_atoms(filter_atoms)
    return kind, target_var, filter_atoms


def _validate_aggregate_filter_atoms(filter_atoms: list[Any]) -> None:
    for atom in filter_atoms:
        if not isinstance(atom, tuple) or not atom:
            raise ProbLogExportError(f"unsupported aggregate filter atom: {atom!r}")
        kind = atom[0]
        if not isinstance(kind, str):
            raise ProbLogExportError(f"unsupported aggregate filter atom kind: {kind}")
        if kind in _AGGREGATE_KINDS:
            raise ProbLogExportError("nested aggregate is not supported in aggregate filter")
        if kind not in _AGGREGATE_FILTER_ATOM_KINDS:
            raise ProbLogExportError(f"unsupported aggregate filter atom kind: {kind}")
        if kind == "not":
            if len(atom) != 2:
                raise ProbLogExportError("not atom must be ('not', body)")
            for branch in _normalize_not_bodies(atom[1]):
                _validate_aggregate_filter_atoms(branch)


def _normalize_not_bodies(not_body: Any) -> list[list[Any]]:
    if not isinstance(not_body, list) or not not_body:
        raise ProbLogExportError("not body must be non-empty list")
    if all(isinstance(entry, list) for entry in not_body):
        branches = [list(branch) for branch in not_body]
        if any(not branch for branch in branches):
            raise ProbLogExportError("not OR branch must be non-empty")
        return branches
    return [list(not_body)]


def _to_problog_term(value: Any) -> str:
    if isinstance(value, str) and value.startswith("$"):
        return _to_problog_var(value)
    return _to_problog_literal(value)


def _to_problog_arith_output(value: Any, kind: str) -> str:
    if not (isinstance(value, str) and value.startswith("$")):
        raise ProbLogExportError(f"{kind} output must be a variable token")
    return _to_problog_var(value)


def _to_problog_arith_term(value: Any) -> str:
    if isinstance(value, str) and value.startswith("$"):
        return _to_problog_var(value)
    if isinstance(value, int) and not isinstance(value, bool):
        return str(value)
    raise ProbLogExportError("arithmetic operands must be variables or integer literals")


def _to_problog_var(token: str) -> str:
    raw = token[1:] if token.startswith("$") else token
    normalized = _VAR_IDENT_RE.sub("_", raw).strip("_")
    if not normalized:
        normalized = "v"
    return f"V_{normalized.upper()}"


def _to_problog_literal(value: Any) -> str:
    if value is None:
        return _to_problog_literal(_NONE_VALUE)
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        return repr(value)
    if isinstance(value, str):
        escaped = value.replace("\\", "\\\\").replace("'", "''")
        return f"'{escaped}'"
    encoded = json.dumps(value, ensure_ascii=False, separators=(",", ":"), sort_keys=True)
    escaped = encoded.replace("\\", "\\\\").replace("'", "''")
    return f"'{escaped}'"
