"""Application-layer modules built on top of core runtime primitives."""

from .capability_helpers import (
    CapabilityHelperError,
    OriginPackageError,
    build_check_request,
    build_diagnose_request,
    build_evaluation_overlay,
    build_fact_remove_action,
    build_fact_value_override,
    build_frontier_view_facts,
    build_proof_frame_recheck_request,
    build_round_event_payload,
    build_rule_add_condition_request,
    build_rule_disable_request,
    build_rule_literal_replace_request,
    build_why_not_candidate_universe,
)
from .derivation_check_runtime import (
    CheckRuntimeError,
    check_derivation_binding,
)
from .derivation_runtime import (
    DerivationRuntimeError,
    accept_derivation_candidate_set,
    accept_derivation_candidate_sets,
    evaluate_derivation_plans,
)
from .diagnose_runtime import (
    DiagnoseRuntimeError,
    diagnose_derivation_binding,
)
from .entity_view import (
    EntityViewError,
    execute_read_request,
    hydrate_entities,
    hydrate_entity,
)
from .entity_write import (
    EntityWriteError,
    apply_write_plan,
    plan_write_command,
)
from .fact_overlay_runtime import check_fact_overlay_binding
from .ingest_runtime import (
    IngestRuntimeError,
    apply_ingest_request,
)
from .walker import (
    AssertionView,
    AtomKeyView,
    FrozenTupleView,
    IRAtomView,
    IRBodyWalker,
    ProofFrameDiffView,
    ProofFrameView,
    SupportArtifactView,
    frozen_collection,
    parse_atom_key,
)
from .workspace_runtime import (
    WORKSPACE_LEDGER,
    WORKSPACE_MANIFEST_NAME,
    WORKSPACE_REGISTRY,
    WORKSPACE_SAVE_SCOPE,
    WORKSPACE_VERSION,
    WorkspacePaths,
    WorkspaceRuntimeError,
    copy_ledger_to_workspace,
    load_workspace,
    resolve_workspace_paths,
    save_workspace,
    save_workspace_manifest,
    sync_registry_to_workspace,
    validate_workspace_manifest,
    workspace_manifest_payload,
)
from .query_runtime import (
    QueryRuntimeError,
    execute_query,
)
from .rule_disable_runtime import check_rule_disable_action
from .rule_add_condition_runtime import check_rule_add_condition_action
from .rule_literal_replace_runtime import check_rule_literal_replace_action
from .proofframe_runtime import (
    recheck_proof_frame,
    render_proof_frame_narrative,
)
from .schema_runtime import (
    EntityTypeInfo,
    FieldTypeInfo,
    IdentityFieldInfo,
    PredicateInfo,
    SchemaIndex,
    SchemaResolutionError,
    build_schema_index,
    encode_entity_ref,
    entity_info,
    entity_type_from_ref,
    field_predicate,
    field_value_type,
    materialize_identity,
    resolve_selector,
)
from .authoring_runtime import AuthoringRuntimeError
from .why_not_runtime import (
    WhyNotRuntimeError,
    check_why_not_universe,
)

__all__ = [
    "AssertionView",
    "AtomKeyView",
    "AuthoringRuntimeError",
    "CheckRuntimeError",
    "CapabilityHelperError",
    "DerivationRuntimeError",
    "DiagnoseRuntimeError",
    "EntityTypeInfo",
    "EntityViewError",
    "EntityWriteError",
    "FieldTypeInfo",
    "FrozenTupleView",
    "IdentityFieldInfo",
    "IngestRuntimeError",
    "IRAtomView",
    "IRBodyWalker",
    "OriginPackageError",
    "PredicateInfo",
    "ProofFrameDiffView",
    "ProofFrameView",
    "QueryRuntimeError",
    "SchemaIndex",
    "SchemaResolutionError",
    "SupportArtifactView",
    "WORKSPACE_LEDGER",
    "WORKSPACE_MANIFEST_NAME",
    "WORKSPACE_REGISTRY",
    "WORKSPACE_SAVE_SCOPE",
    "WORKSPACE_VERSION",
    "WorkspacePaths",
    "WorkspaceRuntimeError",
    "WhyNotRuntimeError",
    "accept_derivation_candidate_set",
    "accept_derivation_candidate_sets",
    "apply_ingest_request",
    "apply_write_plan",
    "build_check_request",
    "build_diagnose_request",
    "build_evaluation_overlay",
    "build_fact_remove_action",
    "build_schema_index",
    "build_fact_value_override",
    "build_frontier_view_facts",
    "build_proof_frame_recheck_request",
    "build_round_event_payload",
    "build_rule_add_condition_request",
    "build_rule_disable_request",
    "build_rule_literal_replace_request",
    "build_why_not_candidate_universe",
    "check_derivation_binding",
    "check_fact_overlay_binding",
    "check_rule_add_condition_action",
    "check_rule_disable_action",
    "check_rule_literal_replace_action",
    "check_why_not_universe",
    "copy_ledger_to_workspace",
    "diagnose_derivation_binding",
    "encode_entity_ref",
    "entity_info",
    "entity_type_from_ref",
    "evaluate_derivation_plans",
    "execute_query",
    "execute_read_request",
    "field_predicate",
    "field_value_type",
    "frozen_collection",
    "hydrate_entities",
    "hydrate_entity",
    "load_workspace",
    "materialize_identity",
    "parse_atom_key",
    "plan_write_command",
    "recheck_proof_frame",
    "render_proof_frame_narrative",
    "resolve_workspace_paths",
    "save_workspace",
    "save_workspace_manifest",
    "resolve_selector",
    "sync_registry_to_workspace",
    "validate_workspace_manifest",
    "workspace_manifest_payload",
]
