from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

from factpy_kernel.adapters.problog.rule_ext import (
    ProbLogRuleExt,
    materialize_problog_branch_probabilities,
)
from factpy_kernel.adapters.souffle.where_compile import extract_where_variables
from factpy_kernel.core.store.runtime import Store

_NONE_VALUE = "__none__"
_VAR_IDENT_RE = re.compile(r"[^A-Za-z0-9_]")


class ProbLogExportError(Exception):
    pass


def export_problog(store: Store, rule_spec: dict[str, Any], out_path: Path) -> None:
    if not isinstance(store, Store):
        raise ProbLogExportError("store must be Store")
    if not isinstance(rule_spec, dict):
        raise ProbLogExportError("rule_spec must be object")

    where = rule_spec.get("where")
    if not isinstance(where, list) or not where:
        raise ProbLogExportError("rule_spec.where must be non-empty list")
    bodies = _normalize_where_bodies(where)
    engine_ext = rule_spec.get("engine_ext")
    if engine_ext is not None and not isinstance(engine_ext, ProbLogRuleExt):
        raise ProbLogExportError(f"rule_spec.engine_ext must be ProbLogRuleExt, got {type(engine_ext).__name__}")
    try:
        branch_probabilities = materialize_problog_branch_probabilities(
            where=where,
            engine_ext=engine_ext,
        )
    except ValueError as exc:
        raise ProbLogExportError(str(exc)) from exc

    try:
        query_vars = extract_where_variables(where)
    except Exception as exc:
        raise ProbLogExportError(f"failed to extract query variables: {exc}") from exc

    lines: list[str] = []
    lines.append("% generated by factpy problog adapter")
    lines.append(f"% query_vars={json.dumps(query_vars, ensure_ascii=False, separators=(',', ':'))}")
    lines.append("")

    active_claims = [
        claim
        for claim in store.ledger.claims
        if not store.ledger.has_active_revocation(claim.asrt_id)
    ]
    active_claims.sort(key=lambda row: row.asrt_id)

    for claim in active_claims:
        prob = _claim_probability(store, claim.asrt_id)
        value_term = _claim_value_term(claim.rest_terms)
        lines.append(
            f"{_format_probability(prob)}::edb_fact("
            f"{_to_problog_literal(claim.asrt_id)}, "
            f"{_to_problog_literal(claim.pred_id)}, "
            f"{_to_problog_literal(claim.e_ref)}, "
            f"{value_term}"
            ")."
        )

    if lines and lines[-1] != "":
        lines.append("")

    for idx, body in enumerate(bodies):
        branch_head = _predicate_call(f"rule_body_{idx}", query_vars)
        compiled_body = _compile_body(body)
        lines.append(f"{_format_probability(branch_probabilities[idx])}::{branch_head} :- {compiled_body}.")

    answer_head = _predicate_call("answer", query_vars)
    for idx in range(len(bodies)):
        branch_head = _predicate_call(f"rule_body_{idx}", query_vars)
        lines.append(f"{answer_head} :- {branch_head}.")
    lines.append(f"query({answer_head}).")

    path = Path(out_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8", newline="\n")


def _normalize_where_bodies(where: list[Any]) -> list[list[Any]]:
    if not where:
        raise ProbLogExportError("where must be non-empty list")
    if all(isinstance(item, list) for item in where):
        bodies = [list(branch) for branch in where]
        if any(not branch for branch in bodies):
            raise ProbLogExportError("where OR branch must be non-empty")
        return bodies
    return [list(where)]


def _claim_probability(store: Store, asrt_id: str) -> float:
    annotations = store.ledger.find_annotations(
        asrt_id=asrt_id,
        namespace="problog",
        category="semantic",
        key="probability",
    )
    if annotations:
        for row in reversed(annotations):
            value = row.value
            if isinstance(value, bool):
                continue
            if isinstance(value, (int, float)):
                prob = float(value)
                if prob <= 0.0 or prob > 1.0:
                    raise ProbLogExportError(
                        f"problog/semantic/probability out of range for asrt_id={asrt_id}: {prob}"
                    )
                return prob
            raise ProbLogExportError(
                f"problog/semantic/probability must be numeric for asrt_id={asrt_id}"
            )

    shared_annotations = store.ledger.find_annotations(
        asrt_id=asrt_id,
        namespace="shared",
        category="semantic",
        key="probability",
    )
    if shared_annotations:
        for row in reversed(shared_annotations):
            value = row.value
            if isinstance(value, bool):
                continue
            if isinstance(value, (int, float)):
                prob = float(value)
                if prob <= 0.0 or prob > 1.0:
                    raise ProbLogExportError(
                        f"shared/semantic/probability out of range for asrt_id={asrt_id}: {prob}"
                    )
                return prob
            raise ProbLogExportError(
                f"shared/semantic/probability must be numeric for asrt_id={asrt_id}"
            )

    candidates = store.ledger.find_meta(asrt_id=asrt_id, key="confidence")
    if not candidates:
        return 1.0

    for row in reversed(candidates):
        value = row.value
        if isinstance(value, bool):
            continue
        if isinstance(value, (int, float)):
            prob = float(value)
            if prob <= 0.0 or prob > 1.0:
                raise ProbLogExportError(f"meta.confidence out of range for asrt_id={asrt_id}: {prob}")
            return prob
    raise ProbLogExportError(f"meta.confidence must be numeric for asrt_id={asrt_id}")


def _claim_value_term(rest_terms: list[tuple[str, Any]]) -> str:
    if not isinstance(rest_terms, list):
        raise ProbLogExportError("claim.rest_terms must be list")
    if len(rest_terms) == 0:
        return _to_problog_literal(_NONE_VALUE)
    if len(rest_terms) == 1:
        tag, value = rest_terms[0]
        return _tagged_value_to_problog_term(str(tag), value)
    encoded = json.dumps(rest_terms, ensure_ascii=False, separators=(",", ":"), sort_keys=True)
    return _to_problog_literal(encoded)


def _tagged_value_to_problog_term(tag: str, value: Any) -> str:
    if tag in {"string", "entity_ref", "uuid"}:
        return _to_problog_literal(str(value))
    if tag in {"int", "time"}:
        if isinstance(value, bool) or not isinstance(value, int):
            raise ProbLogExportError(f"expected int for tag={tag}")
        return str(value)
    if tag == "bool":
        if not isinstance(value, bool):
            raise ProbLogExportError("expected bool for tag=bool")
        return "true" if value else "false"
    if tag == "float64":
        if isinstance(value, bool):
            raise ProbLogExportError("expected float for tag=float64")
        if isinstance(value, float):
            return repr(value)
        if isinstance(value, str):
            return _to_problog_literal(value)
        raise ProbLogExportError("expected float|hex-string for tag=float64")
    if tag in {"bytes", "json"}:
        return _to_problog_literal(json.dumps(value, ensure_ascii=False, separators=(",", ":"), sort_keys=True))
    return _to_problog_literal(str(value))


def _format_probability(prob: float) -> str:
    if isinstance(prob, bool) or not isinstance(prob, float):
        raise ProbLogExportError("probability must be float")
    if prob <= 0.0 or prob > 1.0:
        raise ProbLogExportError("probability must be within (0,1]")
    return f"{prob:.12g}"


def _predicate_call(name: str, vars_in_order: list[str]) -> str:
    if not vars_in_order:
        return name
    args = ", ".join(_to_problog_term(token) for token in vars_in_order)
    return f"{name}({args})"


def _compile_body(body: list[Any]) -> str:
    if not isinstance(body, list) or not body:
        raise ProbLogExportError("where body must be non-empty list")
    return ", ".join(_compile_atom(atom) for atom in body)


def _compile_atom(atom: Any) -> str:
    if not isinstance(atom, tuple) or not atom:
        raise ProbLogExportError(f"unsupported where atom: {atom!r}")
    kind = atom[0]

    if kind == "pred":
        if len(atom) != 3:
            raise ProbLogExportError("pred atom must be ('pred', pred_id, terms)")
        pred_id, terms = atom[1], atom[2]
        if not isinstance(pred_id, str) or not pred_id:
            raise ProbLogExportError("pred_id must be non-empty string")
        if not isinstance(terms, list) or not terms:
            raise ProbLogExportError("pred terms must be non-empty list")
        if len(terms) == 1:
            return (
                "edb_fact(_, "
                f"{_to_problog_literal(pred_id)}, "
                f"{_to_problog_term(terms[0])}, "
                "_)"
            )
        if len(terms) == 2:
            return (
                "edb_fact(_, "
                f"{_to_problog_literal(pred_id)}, "
                f"{_to_problog_term(terms[0])}, "
                f"{_to_problog_term(terms[1])}"
                ")"
            )
        raise ProbLogExportError(f"pred atom arity > 2 is not supported in problog export: {pred_id}")

    if kind == "eq":
        if len(atom) != 3:
            raise ProbLogExportError("eq atom must be ('eq', lhs, rhs)")
        return f"{_to_problog_term(atom[1])} = {_to_problog_term(atom[2])}"

    if kind in {"gt", "ge", "lt", "le"}:
        if len(atom) != 3:
            raise ProbLogExportError(f"{kind} atom must have 2 operands")
        op = {"gt": ">", "ge": ">=", "lt": "<", "le": "=<"}[kind]
        return f"{_to_problog_term(atom[1])} {op} {_to_problog_term(atom[2])}"

    if kind == "in":
        if len(atom) != 3:
            raise ProbLogExportError("in atom must be ('in', var, values)")
        lhs = _to_problog_term(atom[1])
        values = atom[2]
        if not isinstance(values, list) or not values:
            raise ProbLogExportError("in values must be non-empty list")
        parts = [f"{lhs} = {_to_problog_term(value)}" for value in values]
        return f"({' ; '.join(parts)})"

    if kind == "not":
        if len(atom) != 2:
            raise ProbLogExportError("not atom must be ('not', body)")
        not_body = atom[1]
        branches = _normalize_not_bodies(not_body)
        branch_terms = [", ".join(_compile_atom(entry) for entry in branch) for branch in branches]
        if len(branch_terms) == 1:
            inner = branch_terms[0]
        else:
            inner = " ; ".join(f"({term})" for term in branch_terms)
        return f"\\+({inner})"

    raise ProbLogExportError(f"unsupported where atom kind for problog export: {kind}")


def _normalize_not_bodies(not_body: Any) -> list[list[Any]]:
    if not isinstance(not_body, list) or not not_body:
        raise ProbLogExportError("not body must be non-empty list")
    if all(isinstance(entry, list) for entry in not_body):
        branches = [list(branch) for branch in not_body]
        if any(not branch for branch in branches):
            raise ProbLogExportError("not OR branch must be non-empty")
        return branches
    return [list(not_body)]


def _to_problog_term(value: Any) -> str:
    if isinstance(value, str) and value.startswith("$"):
        return _to_problog_var(value)
    return _to_problog_literal(value)


def _to_problog_var(token: str) -> str:
    raw = token[1:] if token.startswith("$") else token
    normalized = _VAR_IDENT_RE.sub("_", raw).strip("_")
    if not normalized:
        normalized = "v"
    return f"V_{normalized.upper()}"


def _to_problog_literal(value: Any) -> str:
    if value is None:
        return _to_problog_literal(_NONE_VALUE)
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        return repr(value)
    if isinstance(value, str):
        escaped = value.replace("\\", "\\\\").replace("'", "''")
        return f"'{escaped}'"
    encoded = json.dumps(value, ensure_ascii=False, separators=(",", ":"), sort_keys=True)
    escaped = encoded.replace("\\", "\\\\").replace("'", "''")
    return f"'{escaped}'"
