from __future__ import annotations

from .authoring_events import (
    AuthoringApplyEvent,
    AuthoringAuditReadError,
    load_authoring_apply_events,
    summarize_authoring_apply_events,
)
from .assertions import AuditAssertionIndex, AuditAssertionReadError, load_assertion_index
from .evidence_graph import (
    EDGE_DERIVES,
    EDGE_SUPPORTS,
    EDGE_UPDATES,
    LAYOUT_TIMELINE,
    LAYOUT_TREE,
    NODE_CONCLUSION,
    NODE_PREMISE,
    NODE_SEED,
    EvidenceEdge,
    EvidenceGraph,
    EvidenceNode,
    evidence_graph_from_dict,
    evidence_graph_to_dict,
    render_evidence_graph_html,
)
from .dto import (
    AuditDTOError,
    build_authoring_apply_run_detail_dto,
    build_authoring_apply_run_list_dto,
    build_candidate_evidence_tree_narrative_dto,
    build_candidate_evidence_tree_summary_dto,
    build_candidate_evidence_tree_dto,
    build_compliance_matrix_dto,
    build_decision_detail_dto,
    build_rule_trace_detail_dto,
    build_rule_trace_detail_payload,
    build_rule_trace_list_dto,
    build_rule_trace_narrative_dto,
    build_rule_trace_summary_dto,
    build_rule_trace_summary_list_dto,
    build_run_detail_dto,
    build_run_list_dto,
)
from .query import AuditOptionalDomainError, AuditQuery, AuditQueryError
from .reader import AuditPackageData, AuditReadError, load_audit_package

# Note: ECSS-specific symbols (AuditComplianceError, ECSS_*, build_compliance_matrix_rows,
# ecss_vcd_predicates, extend_schema_ir_with_ecss_vcd_predicates) moved with compliance.py
# to domains.ecss.compliance during the namespace split.
# Note: render_audit_static_site moved with static_ui.py to service.static_ui.

__all__ = [
    "AuthoringApplyEvent",
    "AuthoringAuditReadError",
    "load_authoring_apply_events",
    "summarize_authoring_apply_events",
    "AuditPackageData",
    "AuditReadError",
    "load_audit_package",
    "AuditAssertionIndex",
    "AuditAssertionReadError",
    "load_assertion_index",
    "LAYOUT_TREE",
    "LAYOUT_TIMELINE",
    "NODE_CONCLUSION",
    "NODE_PREMISE",
    "NODE_SEED",
    "EDGE_SUPPORTS",
    "EDGE_DERIVES",
    "EDGE_UPDATES",
    "EvidenceNode",
    "EvidenceEdge",
    "EvidenceGraph",
    "evidence_graph_to_dict",
    "evidence_graph_from_dict",
    "render_evidence_graph_html",
    "AuditQuery",
    "AuditQueryError",
    "AuditOptionalDomainError",
    "AuditDTOError",
    "build_authoring_apply_run_list_dto",
    "build_authoring_apply_run_detail_dto",
    "build_candidate_evidence_tree_dto",
    "build_candidate_evidence_tree_summary_dto",
    "build_candidate_evidence_tree_narrative_dto",
    "build_run_list_dto",
    "build_run_detail_dto",
    "build_decision_detail_dto",
    "build_compliance_matrix_dto",
    "build_rule_trace_list_dto",
    "build_rule_trace_narrative_dto",
    "build_rule_trace_summary_list_dto",
    "build_rule_trace_summary_dto",
    "build_rule_trace_detail_dto",
    "build_rule_trace_detail_payload",
]
