from __future__ import annotations

# Generic SDK runtime errors
INVALID_ROW_FORMAT = "INVALID_ROW_FORMAT"

# Query runtime errors
QUERY_MISSING_REF = "QUERY_MISSING_REF"
QUERY_TYPE_MISMATCH = "QUERY_TYPE_MISMATCH"
QUERY_ALIAS_CONFLICT = "QUERY_ALIAS_CONFLICT"
QUERY_UNBOUND_VAR = "QUERY_UNBOUND_VAR"
QUERY_INVALID_ROW_FORMAT = "QUERY_INVALID_ROW_FORMAT"
QUERY_NOT_IMPLEMENTED = "QUERY_NOT_IMPLEMENTED"

__all__ = [
    "INVALID_ROW_FORMAT",
    "QUERY_MISSING_REF",
    "QUERY_TYPE_MISMATCH",
    "QUERY_ALIAS_CONFLICT",
    "QUERY_UNBOUND_VAR",
    "QUERY_INVALID_ROW_FORMAT",
    "QUERY_NOT_IMPLEMENTED",
]
