from __future__ import annotations

from typing import Any

CODE_AUTHORING_SCHEMA_COMPILE_ERROR = "authoring_schema_compile_error"
CODE_AUTHORING_SCHEMA_DSL_PARSE_ERROR = "authoring_schema_dsl_parse_error"
CODE_SCHEMA_VALIDATION_ERROR = "schema_validation_error"
CODE_EMPTY_PREDICATES = "empty_predicates"

CODE_REGISTRY_RULE_ERROR = "registry_rule_error"
CODE_RULE_SPEC_ERROR = "rule_spec_error"
CODE_RULE_COMPILE_ERROR = "rule_compile_error"
CODE_AUTHORING_RULE_COMPILE_ERROR = "authoring_rule_compile_error"
CODE_AUTHORING_RULE_DSL_PARSE_ERROR = "authoring_rule_dsl_parse_error"

CODE_DERIVATION_PREVIEW_ERROR = "derivation_preview_error"
CODE_AUTHORING_DERIVATION_COMPILE_ERROR = "authoring_derivation_compile_error"
CODE_AUTHORING_DERIVATION_DSL_PARSE_ERROR = "authoring_derivation_dsl_parse_error"

CODE_PREVIEW_TRUNCATED = "preview_truncated"
CODE_SOUFFLE_BINARY_MISSING = "souffle_binary_missing"
CODE_TEMPORAL_CURRENT_NO_PRED_REFS = "temporal_current_no_pred_refs"
CODE_TEMPORAL_CURRENT_NO_TEMPORAL_SCHEMA_PREDICATES = (
    "temporal_current_no_temporal_schema_predicates"
)
CODE_TEMPORAL_CURRENT_NO_TEMPORAL_WHERE_PREDICATES = (
    "temporal_current_no_temporal_where_predicates"
)
CODE_PUBLISH_BLOCKED_SECTION_ERROR = "publish_blocked_section_error"
CODE_PUBLISH_BLOCKED_MISSING_OR_INVALID_SECTION = "publish_blocked_missing_or_invalid_section"
CODE_PUBLISH_SKIPPED_UNSUPPORTED_SECTION = "publish_skipped_unsupported_section"
CODE_APPLY_BLOCKED_ACTION = "apply_blocked_action"
CODE_APPLY_SKIPPED_ACTION = "apply_skipped_action"
CODE_APPLY_BLOCKED_ACTIONS_PRESENT = "apply_blocked_actions_present"
CODE_APPLY_SKIPPED_ACTIONS_PRESENT = "apply_skipped_actions_present"
CODE_APPLY_PREVALIDATE_BLOCKED_ACTION = "apply_prevalidate_blocked_action"
CODE_APPLY_PREVALIDATE_BLOCKED_ACTIONS_PRESENT = "apply_prevalidate_blocked_actions_present"

AUTHORING_ERROR_CODES_V1 = (
    CODE_AUTHORING_SCHEMA_COMPILE_ERROR,
    CODE_AUTHORING_SCHEMA_DSL_PARSE_ERROR,
    CODE_SCHEMA_VALIDATION_ERROR,
    CODE_REGISTRY_RULE_ERROR,
    CODE_RULE_SPEC_ERROR,
    CODE_RULE_COMPILE_ERROR,
    CODE_AUTHORING_RULE_COMPILE_ERROR,
    CODE_AUTHORING_RULE_DSL_PARSE_ERROR,
    CODE_DERIVATION_PREVIEW_ERROR,
    CODE_AUTHORING_DERIVATION_COMPILE_ERROR,
    CODE_AUTHORING_DERIVATION_DSL_PARSE_ERROR,
    CODE_PUBLISH_BLOCKED_SECTION_ERROR,
    CODE_PUBLISH_BLOCKED_MISSING_OR_INVALID_SECTION,
    CODE_APPLY_BLOCKED_ACTION,
    CODE_APPLY_BLOCKED_ACTIONS_PRESENT,
    CODE_APPLY_PREVALIDATE_BLOCKED_ACTION,
    CODE_APPLY_PREVALIDATE_BLOCKED_ACTIONS_PRESENT,
)

AUTHORING_WARNING_CODES_V1 = (
    CODE_EMPTY_PREDICATES,
    CODE_PREVIEW_TRUNCATED,
    CODE_SOUFFLE_BINARY_MISSING,
    CODE_TEMPORAL_CURRENT_NO_PRED_REFS,
    CODE_TEMPORAL_CURRENT_NO_TEMPORAL_SCHEMA_PREDICATES,
    CODE_TEMPORAL_CURRENT_NO_TEMPORAL_WHERE_PREDICATES,
    CODE_PUBLISH_SKIPPED_UNSUPPORTED_SECTION,
    CODE_APPLY_SKIPPED_ACTION,
    CODE_APPLY_SKIPPED_ACTIONS_PRESENT,
)

AUTHORING_DIAGNOSTIC_CODES_V1 = tuple(
    dict.fromkeys((*AUTHORING_ERROR_CODES_V1, *AUTHORING_WARNING_CODES_V1))
)

AUTHORING_DIAGNOSTIC_CODES_V1_SET = frozenset(AUTHORING_DIAGNOSTIC_CODES_V1)

PHASE_SCHEMA_AUTHORING_COMPILE = "schema.authoring_compile"
PHASE_SCHEMA_DSL_PARSE = "schema.dsl_parse"
PHASE_SCHEMA_VALIDATE = "schema.validate"
PHASE_SCHEMA_PREFLIGHT = "schema.preflight"

PHASE_RULE_DSL_PARSE = "rule.dsl_parse"
PHASE_RULE_REGISTRY = "rule.registry"
PHASE_RULE_PARSE = "rule.parse"
PHASE_RULE_PREFLIGHT = "rule.preflight"
PHASE_RULE_COMPILE = "rule.compile"
PHASE_RULE_AUTHORING_COMPILE = "rule.authoring_compile"

PHASE_DERIVATION_PREVIEW_ENV = "derivation.preview.env"
PHASE_DERIVATION_PREVIEW = "derivation.preview"
PHASE_DERIVATION_AUTHORING_COMPILE = "derivation.authoring_compile"
PHASE_DERIVATION_DSL_PARSE = "derivation.dsl_parse"
PHASE_PUBLISH_PLAN = "publish.plan"
PHASE_PUBLISH_APPLY = "publish.apply"

AUTHORING_DIAGNOSTIC_PHASES_V1 = (
    PHASE_SCHEMA_AUTHORING_COMPILE,
    PHASE_SCHEMA_DSL_PARSE,
    PHASE_SCHEMA_VALIDATE,
    PHASE_SCHEMA_PREFLIGHT,
    PHASE_RULE_DSL_PARSE,
    PHASE_RULE_REGISTRY,
    PHASE_RULE_PARSE,
    PHASE_RULE_PREFLIGHT,
    PHASE_RULE_COMPILE,
    PHASE_RULE_AUTHORING_COMPILE,
    PHASE_DERIVATION_PREVIEW_ENV,
    PHASE_DERIVATION_PREVIEW,
    PHASE_DERIVATION_AUTHORING_COMPILE,
    PHASE_DERIVATION_DSL_PARSE,
    PHASE_PUBLISH_PLAN,
    PHASE_PUBLISH_APPLY,
)

AUTHORING_DIAGNOSTIC_PHASES_V1_SET = frozenset(AUTHORING_DIAGNOSTIC_PHASES_V1)


def build_diagnostics_contract_meta_v1() -> dict[str, Any]:
    return {
        "diagnostics_contract_version": "authoring_diagnostics_contract_v1",
        "codes": list(AUTHORING_DIAGNOSTIC_CODES_V1),
        "phases": list(AUTHORING_DIAGNOSTIC_PHASES_V1),
    }
