from __future__ import annotations

from .compile import (
    build_authoring_schema_from_classes,
    compile_schema_from_classes,
    schema_preflight_from_classes,
)
from .errors import (
    CardinalityError,
    EditorClosedError,
    EntityAlreadyExistsError,
    EntityNotFoundError,
    FrozenSnapshotError,
    SchemaConflictError,
    SchemaNonAdditiveError,
    SchemaNotFoundError,
    SDKSchemaError,
    SDKStoreError,
    SDKValueError,
)
from .error_codes import (
    INVALID_ROW_FORMAT,
    QUERY_ALIAS_CONFLICT,
    QUERY_INVALID_ROW_FORMAT,
    QUERY_MISSING_REF,
    QUERY_NOT_IMPLEMENTED,
    QUERY_TYPE_MISMATCH,
    QUERY_UNBOUND_VAR,
)
from .schema import Entity, Field, Identity, Relationship
from .semantics import ProbLogSemantics, PyReasonSemantics
from .store import FactGraph, SDKStore
from factgraph.application.protocol import (
    AtomDescriptor,
    Claim,
    DetachedRowError,
    EvaluateResult,
    EvaluateRow,
    EvidenceRef,
    Explanation,
    ExplicitBoolError,
    OccurrenceInspect,
    PortInspect,
    Rule,
    RuleExpr,
    RuleExprError,
    RuleExprInspect,
    RuleJoinConstraint,
)
from factgraph.application.schema_mutation_runtime import SchemaAddResult
from factgraph.core.semantics import SemanticsProfile
from factgraph.core.store import AssertionInput, CommitResult, Database, MetaEntry
from .dsl import (
    Case,
    DSLToApplicationRuleError,
    EmitSpec,
    Inference,
    Not,
    Pred,
    Query,
    RuleRef,
    SDKDSLError,
    build_application_rule,
    vars,
)
from .ingest import IngestResult, ValidationReport

ApplicationRule = Rule

__all__ = [
    "SDKSchemaError",
    "SDKStoreError",
    "SDKValueError",
    "EntityAlreadyExistsError",
    "EntityNotFoundError",
    "FrozenSnapshotError",
    "SchemaConflictError",
    "SchemaNonAdditiveError",
    "SchemaNotFoundError",
    "CardinalityError",
    "EditorClosedError",
    "INVALID_ROW_FORMAT",
    "QUERY_MISSING_REF",
    "QUERY_TYPE_MISMATCH",
    "QUERY_ALIAS_CONFLICT",
    "QUERY_UNBOUND_VAR",
    "QUERY_INVALID_ROW_FORMAT",
    "QUERY_NOT_IMPLEMENTED",
    "IngestResult",
    "ValidationReport",
    "SDKDSLError",
    "Case",
    "Entity",
    "Field",
    "Identity",
    "Relationship",
    "SemanticsProfile",
    "Claim",
    "DetachedRowError",
    "EvaluateResult",
    "EvaluateRow",
    "EvidenceRef",
    "Explanation",
    "ProbLogSemantics",
    "PyReasonSemantics",
    "SchemaAddResult",
    "AssertionInput",
    "CommitResult",
    "Database",
    "MetaEntry",
    "Rule",
    "ApplicationRule",
    "RuleRef",
    "EmitSpec",
    "Inference",
    "Query",
    "Pred",
    "Not",
    "vars",
    "build_application_rule",
    "DSLToApplicationRuleError",
    "RuleExprInspect",
    "OccurrenceInspect",
    "AtomDescriptor",
    "PortInspect",
    "RuleExpr",
    "RuleExprError",
    "RuleJoinConstraint",
    "ExplicitBoolError",
    "FactGraph",
    "SDKStore",
    "build_authoring_schema_from_classes",
    "compile_schema_from_classes",
    "schema_preflight_from_classes",
]
